Some useful imports.

In [5]:
import numpy as np

"""# Import Sionna
try:
    import sionna
except ImportError as e:
    # Install Sionna if package is not already installed
    import os
    os.system("pip install sionna")
    import sionna
import tensorflow as tf"""

from utils import CDMA_encode, CDMA_decode, random_data, Binary2PlusMinusOne, PlusMinusOne2Binary, generate_bit_sequences, random_code
import matplotlib.pyplot as plt
from termcolor import colored
from scipy.special import erfc

class bcolors:
    OK = "\033[92m"  # GREEN
    WARNING = "\033[93m"  # YELLOW
    FAIL = "\033[91m"  # RED
    RESET = "\033[0m"  # RESET COLOR

Input data and used parameters.

In [6]:
tx_params = {
    "nUsers" : 4,
    "powerAllocation" : np.zeros(3),
    "nMessage" : 3,
    "cCode" : 3,
    "correctorRate" : 1/2,
    "nCodeCDMA" : 8,
    "symb_freq" : 25e3,
    "codes" : []
}

data = random_data(tx_params)
data_out = CDMA_encode(data, tx_params)
data_estimated = CDMA_decode(data_out, tx_params)
for i in range(tx_params["nUsers"]):
    data[i] = PlusMinusOne2Binary(data[i], int)

print("We want to transmit the following data to "+str(tx_params["nUsers"])+" users.")
print(data)
print("Therefore we encode via CDMA and we get the following no-noise channel.")
print(data_out)
print("Finally this is the estimated transmitted data from the CDMA decoder.")
print(data_estimated)

if((data_estimated==data).all()) : 
    print(bcolors.OK + "Well Done !" + bcolors.RESET)
else : 
    print(bcolors.WARNING + "Try Again..." + bcolors.RESET)

We want to transmit the following data to 4 users.
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 1.]]
Therefore we encode via CDMA and we get the following no-noise channel.
[ 0.  0.  0.  0.  0.  0. -4. -4.  0.  0.  0.  0.  0.  0.  4.  4.  0.  0.
  4.  4.  0.  0.  0.  0.]
Finally this is the estimated transmitted data from the CDMA decoder.
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 1.]]
Well Done !
